<?php

/**
 * @file
 * Enable Parallax effect for any block created by the user.
 *
 * This module enables the user to select none, Same, or Opposite directions
 * when creating a block. Selecting Same or Opposite places a data attribute
 * which is ready by the attached javascript file, and then targeted for
 * calculations causing parallax effect based on 'same' or 'opposite' value.
 */

/**
 * Implements hook_form_alter().
 */
function parallax_tutorial_form_alter(&$form, &$form_state, $form_id) {
  if (($form_id == 'block_admin_configure') || ($form_id == 'block_add_block_form')) {
    $block = block_load($form['module']['#value'], $form['delta']['#value']);

    $form['settings']['parallax'] = array(
      '#type'         => 'fieldset',
      '#title'        => t('Parallax Settings'),
      '#collapsible'  => TRUE,
      '#collapsed'    => TRUE,
    );

    $form['settings']['parallax']['parallax_value'] = array(
      '#title'    => t('Parallax Direction'),
      '#type'     => 'select',
      '#options'  => array(
        'none' => t('None'),
        'top-to-bottom' => t('Move to bottom on scroll (fast effect)'),
        'bottom-to-top' => t('Move to top on scroll (slow effect)'),
      ),
      '#default_value' => isset($block->parallax_value) ? $block->parallax_value : 'none',
    );

    $form['settings']['parallax']['background_image'] = array(
      '#title'                => t('Background Image'),
      '#type'                 => 'managed_file',
      '#description'          => t('Replace all spaces in file name with dashes. Larger pictures are recommended.'),
      '#default_value'        => isset($block->background_image) ? $block->background_image : '',
      '#upload_location'      => 'public://parallax_block/',
      '#upload_validators'    => array(
        'file_validate_extensions' => array('gif png jpg jpeg'),
        'file_validate_size'  => array(2 * 1024 * 1024),
      ),
    );

    $form['#submit'][] = 'parallax_tutorial_form_submit';
  }
}
